In [1]:
import numpy as np
import matplotlib as mpl
import pandas as pd

In [41]:
americanDrugUsageData = pd.read_csv("drug_usage.csv", sep=",")
#Duidelijke benamingen
americanDrugUsageData.columns = ['Staat','Populatie', 'Drugs gebruikers %', 'Doden', 'Doden per 100,00', 'Subsidie', 'Subsidie per gebruiker']
#Verwijderen van onnodige data
del americanDrugUsageData['Doden']
del americanDrugUsageData['Doden per 100,00']
del americanDrugUsageData['Subsidie']
del americanDrugUsageData['Subsidie per gebruiker']
#Schoonmaken van de extra karakters bij percentage
americanDrugUsageData['Drugs gebruikers %'] = americanDrugUsageData['Drugs gebruikers %'].str.split('%', n = 1, expand = True)[0]
americanDrugUsageData

                   Staat    Populatie Drugs gebruikers %
0                Alabama    4,779,736              06.73
1                 Alaska      710,231              11.79
2                Arizona    6,392,017              08.95
3               Arkansas    2,915,918              07.96
4             California   37,253,956              09.07
5               Colorado    5,029,196              11.72
6            Connecticut    3,574,097              08.23
7               Delaware      897,934              09.14
8                Florida   18,801,310              07.80
9   Georgia (U.S. state)    9,687,653              07.32
10                Hawaii    1,360,301              09.92
11                 Idaho    1,567,582              08.00
12              Illinois   12,830,632              07.17
13               Indiana    6,483,802              08.79
14                  Iowa    3,046,355              04.08
15                Kansas    2,853,118              06.77
16              Kentucky    4,339,367              08.41
17             Louisiana    4,533,372              07.16
18                 Maine    1,328,361              09.09
19              Maryland    5,773,552              07.29
20         Massachusetts    6,547,629              08.87
21              Michigan    9,883,640              08.95
22             Minnesota    5,303,925              08.24
23           Mississippi    2,967,297              06.39
24              Missouri    5,988,927              07.38
25               Montana      989,415              10.02
26              Nebraska    1,826,341              06.43
27                Nevada    2,700,551              09.35
28         New Hampshire    1,316,470              12.15
29            New Jersey    8,791,894              06.42
30            New Mexico    2,059,179              10.07
31              New York   19,378,102              09.82
32        North Carolina    9,535,483              08.88
33          North Dakota      672,591               05.3
34                  Ohio   11,536,504              07.61
35              Oklahoma    3,751,351              08.09
36                Oregon    3,831,074              12.80
37          Pennsylvania   12,702,379              06.57
38          Rhode Island    1,052,567              13.34
39        South Carolina    4,625,364              06.70
40          South Dakota      814,180              06.28
41             Tennessee    6,346,105              08.22
42                 Texas   25,145,561              06.26
43                  Utah    2,763,885              06.24
44               Vermont      625,741              13.73
45              Virginia    8,001,024              07.33
46            Washington    6,724,540              09.59
47         West Virginia    1,852,994              06.79
48             Wisconsin    5,686,986              08.67
49               Wyoming      563,626              06.82
50         United States  308,143,815              08.11